### PR TITLE
Removed husky

### PR DESCRIPTION
**Pull request by gergoradeczki**
title

### CODE REVIEW

**Comment by kripod** [comment]
Hello,

Thanks for submitting this PR. Husky is added for a reason, making sure that files are formatted properly and have no linting errors before being pushed to a branch. This could save precious CI time and warn developers early about their mistakes.

You may use [`git commit --no-verify`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---no-verify) as an escape hatch, e.g. when heavy refactorings are being made through consecutive commits.

**Comment by gergoradeczki** [comment]
image

I am unable to commit without using the `--no-verify` flag. I have no idea what's wrong with Husky, but if I have to always rely on this flag then Husky becomes obsolete.

What seems to solve this issue is disabling the shell script or removing Husky.

**Comment by kripod** [comment]
You may want to create your own fork of this template where you could remove Husky. The issue isn’t with Husky itself, as it works as intended both on my machine and CI.

**Comment by gergoradeczki** [comment]
I would recommend to add a warning to the README.md which states that this setup is not intended to use on Windows machines "out of the box" (eg. requires other programs / disabling the shell script).

**Comment by kripod** [comment]
Last time I tried Husky on Windows, it did work. Please make sure that your git installation comes with a UNIX-compatible shell, as noted [in Husky’s docs](https://typicode.github.io/husky/#/?id=does-it-work-on-windows).

**Pull request closed without merging**
